version: "3"

services:
  app1:
    image: docker.io/nginx:mainline
    networks:
      - services
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.stripapp1.stripprefix.prefixes=/app1"
      - "traefik.http.routers.app1.rule=PathPrefix(`/app1`)"
      - "traefik.http.routers.app1.middlewares=stripapp1"
    volumes:
      - "./htdocs:/usr/share/nginx/html"



networks:
  services:
    external: true
