version: "3"

services:
  traefik:
    image: traefik:latest
    networks:
      - services
    command:
      - --api.insecure=true
      - --providers.docker
      - --accesslog=true
      - --accesslog.filepath=/dev/stderr
      - --providers.docker.exposedByDefault=false
    ports:
      - "127.0.0.2:80:80"
      - "127.0.0.2:443:443"
      - "127.0.0.2:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  services:
    external: true
